### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by Samukinha-ponto-exe** [doki-theme/doki-theme-vim#26]
I love the doki-theme. I use it on vscode, hyper and webstorm. But I use neovim instead of vim. 
I would like to know if it supports doki-theme and if so, if the installation process is the same as for vim. 
I'm a brazilian guy, so sorry for my bad english.

Thank you so much for your amazing work for the otaku community. ❤️

**Comment by Unthrottled** [comment]
I like the idea, I've been wanting to carve out time to refactor the current themes to more align to my now standardized syntax highlighting scheme.

I'll look into seeing what needs to be done to support neovim, or if it needs a new plugin. Thanks!

**Comment by Unthrottled** [comment]
@Samukinha-ponto-exe 

Alright, I've got most of it taken care of, you should be able to follow the [instructions here](https://github.com/doki-theme/doki-theme-vim/tree/v15.0.0#neovim) (provided you use a Unix like operating system).

You should also install any of the [supported plugins](https://github.com/doki-theme/doki-theme-vim/tree/v15.0.0#supported-plugins), if they are relevant to what you do.

I've verified it works for my NeoVim

![Screenshot from 2022-01-04 06-15-46](https://user-images.githubusercontent.com/15972415/148057748-8074f098-6364-436d-846c-7a0cbb4beafb.png)

**Comment by Samukinha-ponto-exe** [comment]
Thank's dude! God bless you
