### ISSUE TITLE
C/C++ syntax highlighting 

### ISSUE THREAD

**Issue by KonniLol** [doki-theme/doki-theme-vim#30]
I use C/C++ and really like your color schemes but the C and C++ highlighting is quite... minimalistic.
I hope you can add support soon.

**Comment by Unthrottled** [comment]
Do you use a plugin for C/C++ ([like this](https://github.com/bfrg/vim-cpp-modern)) or just out-of-the-box vim syntax highlighting?

**Comment by KonniLol** [comment]
Currently I'm using the vanilla neovim highlighting with your colorschemes until I find a plugin written in lua (I heard that neovim has better lua support and it is better for some reason). 
I'm switching from vscodium to neovim and don't know yet how everything works. So I'm sorry if what I wrote doesn't make any sense... :)

**Comment by Unthrottled** [comment]
Hey!

So I've had some time to look into the issue. 

It looks like this isn't an issue with the theme itself, but the vanilla neovim experience. There apparently isn't any thing out of the box that parses the language and adds highlighting to it.

So I installed [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) on my nvim 0.6.1 and the latest doki-theme-vim.

| Before | After |
| --- | --- |
|![Screenshot from 2022-04-05 18-15-38](https://user-images.githubusercontent.com/15972415/161960553-99f2bbc5-f6d6-407a-9893-5a11bf3c7580.png) | ![Screenshot from 2022-04-06 05-56-45](https://user-images.githubusercontent.com/15972415/161960600-c6ef84f1-5342-496c-bd45-2192574ab9d8.png) |

It doesn't look like the official Doki Theme syntax highlighting scheme, but it is more colorful. I don't use vim for development, so I'm not going to invest any time into making the tree sitter look official.

I'm going to close this issue. Let me know if you need anymore information on how to get that setup.

By the way, just vim and [vim-cpp-modern](https://github.com/bfrg/vim-cpp-modern) looks okay-ish. At least more like the official highlighting scheme.

![Screenshot from 2022-04-06 06-04-17](https://user-images.githubusercontent.com/15972415/161961230-05f2fbe7-e9d7-4276-8e9b-f3adb00362af.png)
