### ISSUE TITLE
I cannot install package because 'packpath' was not found

### ISSUE THREAD

**Issue by Antonio-Scarface** [doki-theme/doki-theme-vim#34]
Error executing C:\Users\Windows\AppData\Local\nvim\init.vim:
line 200:
E919: Directory not found in 'packpath': "pack/*/opt/doki-theme"

**Comment by Unthrottled** [comment]
Huh, I'll assume you are on windows 10 trying to use neovim.

You think you can start from scratch? Here is what I did.

---

1. Downloaded the windows zip from here https://github.com/neovim/neovim/releases/tag/v0.7.0
2. Extracted the file contents in the `C:\Program Files\Neovim` folder
![image](https://user-images.githubusercontent.com/15972415/164113688-fa2e9590-7574-41c4-812e-a0d1dd216e7a.png)
3. Added `C:\Program Files\Neovim` to the environment variable `PATH`
![image](https://user-images.githubusercontent.com/15972415/164113786-73f74c88-c88c-4662-b7b3-950bdbd66f8f.png)
4. Ran `nvim` in a command prompt and run the editor command `:echo stdpath('config')`
![image](https://user-images.githubusercontent.com/15972415/164113932-6ed8bf36-aafc-4de5-8a93-33d79e500730.png)
5. Create the directories if they don't already exist.
6. Install [vim-plug](https://github.com/junegunn/vim-plug#windows-powershell-1) using windows powershell.
7. Add a `init.vim` in the directory you got from step 4.
8. Add this in your `init.vim`
```vims
call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/doki-theme/doki-theme-vim
Plug 'doki-theme/doki-theme-vim'


" Initialize plugin system
call plug#end()
```
9. (Close NeoVim) Open up `nvim` again and run `:PlugInstall` 
10. One complete, you can run `:colorscheme ` command and that should have tab completion
![image](https://user-images.githubusercontent.com/15972415/164114627-507316cc-c527-452c-8edc-8214b66d2010.png)
11. ???
12. profit

---

Let me know if that works, and I can add it to the docs.

**Comment by Antonio-Scarface** [comment]
No, it doesn't work... It gives me always the same output
Despite this, I already have some config files of nvim on my pc so I didn't reinstalled Neovim (so maybe for someone it could work)
Reading ur comment, I found that the only thing that I didn't was adding the config directory to PATH environment, so I did it, but I didn't resolve the problem, as I said at the beginning of the comment
So... have u got some other ideas?? Pls tell me soon

**Comment by Antonio-Scarface** [comment]
Btw, I got that menu when I write `:colorscheme` + `ctrl + D`, but only the colors of the words... the error remains and the background remain the default one

**Comment by Unthrottled** [comment]
> directory to PATH environment, so I did it, but I didn't resolve the problem, as I said at the beginning of the comment

Yeah all that does is as `nvim` to your cmd prompt, so that wouldn't fix it.

> So... have u got some other ideas?? 

I considering you didn't do any of the things that I told you try, and you haven't told me how you configured your neovim or even how you tried to install the plugin, your guess is as good as mine as to what is wrong 😃 

I would start by undoing whatever you did to install the plugin (before submitting this issue) and attempt to install doki-theme vim using vim-plug (I referenced that in my first comment).

>Btw, I got that menu when I write :colorscheme + ctrl + D, but change only the colors of the words... the error remains 

Are you saying you have the doki-theme-vim colors in the drop down (eg `aqua`, `astolfo`, etc)?

>  background remain the default one

That's a feature of [doki-theme-vim](https://github.com/doki-theme/doki-theme-hyper#feature-preview). 


---

I'm going to close this issue because it isn't an issue with the plugin itself, but an issue with your local installation. If you need any additional help, please provide information on how you attempted to install this plugin, how your neovim manages plugins, any configurtion you've updated, because otherwise I can't be of much help, other than saying "I dunno, it works on my machine 🤷"

**Comment by Antonio-Scarface** [comment]
> are you saying you have the doki-theme-vim colors in the drop down (eg aqua, astolfo, etc)?
Yes I have, but only colours.. not as ur background of 02... i see that u have just neovim so the background should be the doki-theme one

**Comment by Antonio-Scarface** [comment]
Yes I have, but only colours.. not as ur background of 02... i see that u have just neovim so the background should be the doki-theme one

**Comment by Antonio-Scarface** [comment]
here is my init.vim file
```
set encoding=utf-8
set termguicolors
set scrolloff=7
set autoindent
set noswapfile
set winblend=0

set wildoptions=pum
set background=dark


syntax enable
call plug#begin('C:/Users/Windows/AppData/Local/nvim/autoload/plugged')
Plug 'https://github.com/scrooloose/nerdtree'
Plug 'https://gitlab.com/debyly/iodide-vim-communicator.git'
Plug '/nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'glepnir/lspsaga.nvim'
Plug 'https://github.com/doki-theme/doki-theme-vim'
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-fugitive'
Plug 'leafgarland/typescript-vim'
Plug 'vim-utils/vim-man'
Plug 'mbbill/undotree'
Plug 'https://github.com/kien/ctrlp.vim'
Plug 'preservim/nerdcommenter'
Plug 'jaxbot/semantic-highlight.vim'
Plug 'roxma/nvim-completion-manager'
Plug 'SirVer/ultisnips'
Plug 'EdenEast/nightfox.nvim'
Plug 'https://github.com/doomemacs/themes'
Plug 'honza/vim-snippets'
Plug 'https://github.com/neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
_here goes some configuration of coc.nvim (but this is not the problem_
call plug#end()
let NERDtTreeQuitOnOpen=1
let NERDTreeMinimalUI=1

packadd! doki-theme
syntax enable
colorscheme rias_crimson
```

**Comment by Antonio-Scarface** [comment]
here is my plug.vim file
`if has("nvim")
        let g:plug_home = stdpath('data') . '/.plugged'
endif

call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'cohama/lexima.vim'

if has("nvim")
        Plug '/neovim/nvim-lspconfig'
        Plug 'glepnir/lspsaga.nvim'
        Plug 'nvim-lua/completion-nvim'
        Plug '/nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
endif

call plug#end()

let g:plug_home = stdpath("data") . "/plugged"

call plug#begin(plug_home)`

**Comment by Antonio-Scarface** [comment]
Here is my directory:
![Screenshot (150)](https://user-images.githubusercontent.com/95542496/164446069-37366ebe-5440-44c4-baa9-8e2335d3e63d.png)

**Comment by Unthrottled** [comment]
Change your `plug.vim` file to look like this:

```vim
if has("nvim")
        let g:plug_home = stdpath('data') . '/.plugged'
endif

call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'cohama/lexima.vim'
Plug 'doki-theme/doki-theme-vim'

if has("nvim")
        Plug '/neovim/nvim-lspconfig'
        Plug 'glepnir/lspsaga.nvim'
        Plug 'nvim-lua/completion-nvim'
        Plug '/nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
endif

call plug#end()

let g:plug_home = stdpath("data") . "/plugged"

call plug#begin(plug_home)
```

I just added `Plug 'doki-theme/doki-theme-vim'` below `Plug 'cohama/lexima.vim'`. 

Once you remove this from your `init.vim`:

```
packadd! doki-theme
syntax enable
``` 

This error should go away.

```
Error executing C:\Users\Windows\AppData\Local\nvim\init.vim:
line 200:
E919: Directory not found in 'packpath': "pack/*/opt/doki-theme"
```

Also be sure to run `:PlugInstall` in NeoVim

**Comment by Antonio-Scarface** [comment]
I tried to do this but I can't install plugins written into plug.vim file (the output of `:PlugInstall` is like I have installed any new plugins)... the fun fact is that I couldn't do that from a day that I was trying to configure neovim with some plugins (like telescope), and i couldn't install for no reason
If u know why u can solve me a lot of other issues too! Pls tell me if u know!

**Comment by Antonio-Scarface** [comment]
This is the output:
 
```
Updated. Elapsed time: 0.512548 sec.                    
  2 [==================]                                    
  3                                                         
  4 - Finishing ... Done!                                   
  5 - lspsaga.nvim: Already installed                       
  6 - ultisnips: Already installed                          
  7 - vim-snippets: Already installed                       
  8 - nvim-treesitter: Already installed                    
  9 - coc.nvim: Already installed                           
 10 - semantic-highlight.vim: Already installed             
 11 - nerdtree: Already installed                           
 12 - nvim-completion-manager: Already installed            
 13 - vim-fugitive: Already installed                       
 14 - typescript-vim: Already installed                    
 15 - vim-man: Already installed                            
 16 - iodide-vim-communicator: Already installed            
 17 - gruvbox: Already installed                            
 18 - nightfox.nvim: Already installed                      
 19 - themes: Already installed                             
 20 - nerdcommenter: Already installed                      
 21 - undotree: Already installed                           
 22 - ctrlp.vim: Already installed

```

**Comment by Unthrottled** [comment]
> I tried to do this but I can't install plugins written into plug.vim file (the output of :PlugInstall is like I have installed any new plugins)... 

I think it might be ignoring your `plug.vim` file. Why don't you try adding `Plug 'doki-theme/doki-theme-vim'` below `Plug 'leafgarland/typescript-vim'`, and run an install again.

**Comment by Antonio-Scarface** [comment]
I have already did this... in fact, as i said, I can see the colour theme changing, but not the background; here is how it looks like with `:colorscheme rias_crimson`:
![Screenshot (151)](https://user-images.githubusercontent.com/95542496/164469019-2dadcd03-d848-4b91-bfc8-b3649748817f.png)

**Comment by Antonio-Scarface** [comment]
Hey I have resolved the issue with plug.vim... it was because i wrote `:source %` into it, so it didn't read it... however, the colorscheme remains always the same as the cmd photo that i sent to u... no background as ur 02 one

**Comment by Unthrottled** [comment]
>no background as ur 02 one

That's a feature of [doki-theme-hyper](https://github.com/doki-theme/doki-theme-hyper#feature-preview).  Download [hyper.js](https://hyper.is), and install the Doki Theme plugin there and then you'll have the background image when using a terminal.

---

Tip: if you try `hyper i doki-theme-hyper` and it complains about hyper isn't a command just add hyper to the path

![image](https://user-images.githubusercontent.com/15972415/164512317-8d6f85d1-5b8c-4333-9755-cacae71a9e4f.png)

**Comment by Antonio-Scarface** [comment]
Now I have solved the problem... the fun fact is that it was an easy problem: i wasn't using hyper. I was using Windows Terminal
