### ISSUE TITLE
Use another colorscheme and the anime's backgrounds

### ISSUE THREAD

**Issue by NiiSV811** [doki-theme/doki-theme-vim#42]
Hey there. It's just a question, not a issue xd. Is there a way to use One Dark colorscheme and the anime backgrounds?.

Thank You and srry for my english.

**Comment by Unthrottled** [comment]
No Worries :)

You have some options:

- [You can install Doki Theme for Hyper.js](https://github.com/doki-theme/doki-theme-hyper#readme)
- You can find another terminal that allows you to have a background image set. I don't have any handy (sorry)

Hope that helps.
